name: Deploy
on:
  push:
    branches: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install --legacy-peer-deps
      - run: npm run build

      - uses: denoland/deployctl@v1
        with:
          project: getwarp
          entrypoint: jsr:@deno/nextjs-start/v15
          root: .
          include: |
            .next
            public
